#!/bin/bash
LOCAL_PATH=$PATH
SEARCH="node/bin"
CURRENT_DIR=$(cd $(dirname "$0"); pwd)

if [ "${LOCAL_PATH/$SEARCH}" = "$LOCAL_PATH" ] ; then
  export PATH=$PATH:${CURRENT_DIR}/vendor/node/bin
fi

if [ "${LOCAL_PATH/"node_modules/.bin"}" = "$LOCAL_PATH" ] ; then
  export PATH=$PATH:${CURRENT_DIR}/node_modules/.bin
fi

gulp "$@"
