#!/bin/bash

VERSION=0.12.0
PLATFORM=linux
ARCH=x64
LOCAL_PATH=$PATH
SEARCH="node/bin"
CURRENT_DIR=$(cd $(dirname "$0"); pwd)
#PREFIX="$HOME/node-v$VERSION-$PLATFORM-$ARCH"
VERSIONSTRING="node-v$VERSION-$PLATFORM-$ARCH"
PREFIX="${CURRENT_DIR}/vendor/node"

if [ ! -f "$PREFIX/$VERSIONSTRING" ]; then
  if [ -d $PREFIX ]; then
    rm -R $PREFIX
  fi

  mkdir -p "$PREFIX" && curl http://nodejs.org/dist/v$VERSION/node-v$VERSION-$PLATFORM-$ARCH.tar.gz | tar xzvf - --strip-components=1 -C "$PREFIX"
  touch $PREFIX/$VERSIONSTRING
fi

if [ "${LOCAL_PATH/$SEARCH}" = "$LOCAL_PATH" ] ; then
  export PATH=$PATH:${CURRENT_DIR}/vendor/node/bin
fi

# this fixes our internal ssl cert problems
npm config set registry http://registry.npmjs.org/
npm config set ca ""

# install gulp and modules
npm install
